### Scikit Learn
Scikit-learn is an open source Python library to get all algos of machicne learning under one library. You can write any model in ml , train and test it

In [1]:
import sklearn
print('SKlearn version =',sklearn.__version__)

SKlearn version = 1.1.2


### Load Data 
We would be using IRIS DATASET from Scikit-learn, We will see a Linear Regression Model and also will develop a Function for LR. Before that,Let's know more on the dataset.  
_______
 <img src='https://editor.analyticsvidhya.com/uploads/51518iris%20img1.png' width= '500' height='400' 
      align='center'>
### Data Set Characteristics:

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class( Output ):
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica

    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
    :Class Distribution: 33.3% for each of 3 classes.
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken from Fisher's paper.The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant. One class is linearly separable from the other 2; the latter are NOT linearly separable from each other.

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
import pandas as pd
import numpy as np

In [9]:
pd.DataFrame(iris.data, columns=iris.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [12]:
iris.target #class are named for targets (mostly the one which we have to predict)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [13]:
pd.Series(iris.target)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Length: 150, dtype: int64

In [14]:
# name the dataframe
irisdb = pd.DataFrame(iris.data, columns=iris.feature_names)
irisdb['class'] = iris.target

In [15]:
irisdb.sample(6)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
142                5.8               2.7                5.1               1.9   
1                  4.9               3.0                1.4               0.2   
106                4.9               2.5                4.5               1.7   
51                 6.4               3.2                4.5               1.5   
12                 4.8               3.0                1.4               0.1   
95                 5.7               3.0                4.2               1.2   

     class  
142      2  
1        0  
106      2  
51       1  
12       0  
95       1

In [16]:
import seaborn as sns
sns.load_dataset('iris').sample(6)

sepal_length  sepal_width  petal_length  petal_width     species
25            5.0          3.0           1.6          0.2      setosa
73            6.1          2.8           4.7          1.2  versicolor
127           6.1          3.0           4.9          1.8   virginica
129           7.2          3.0           5.8          1.6   virginica
66            5.6          3.0           4.5          1.5  versicolor
41            4.5          2.3           1.3          0.3      setosa

### Features − The variables of data are called its features. They are also known as predictors, inputs or attributes.
Feature matrix − It is the collection of features, in case there are more than one., cols on basis of what we predict output
Feature Names − It is the list of all the names of the features.

In [17]:
feature_matrix = iris.data # data is thr matrix
feature_matrix[:5] #first 5 data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [18]:
feature_names = iris.feature_names # name of column or feature
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

### Response − It is the output variable that basically depends upon the feature variables. They are also known as target, label or output.
Response Vector − It is used to represent response column. Generally, we have just one response column.
Target Names − It represent the possible values taken by a response vector.

In [20]:
target_matrix = iris.target # the class what you will predict 
target_matrix

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
target_names = iris.target_names
target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
# Let's Seperate the Feature and Target as X and y
X = iris.data # feature_matrix
y = iris.target # target_matrix


![Welms Banner](https://tse1.mm.bing.net/th/id/OIP.-ikwdQvFTTBP7utgpzGfzAHaDK?rs=1&pid=ImgDetMain&o=7&rm=3)
## Preparing Data for Modelling

 * Training Dataset : Using the training dataset a model is trained or build.
 * Testing Data set : Portion of data which is not used in training nor in evaluation part
 * Validation data set: Accurate dataset of the model on the useen dataset

By using Train test Split we can seperate the training and testing dataset
```python
 from sklearn.model_selection import train_test_split
     X_train, X_test, y_train, y_test = train_test_split(X, y, train/test_size, random_state)
```
        
        
```python
* X_train : the matrix used for training
* X_test : used for predictions
* y_train: output for the matrix X_train for trainning model
* y_test : evaluation will be made with y_test and predictions
* random_state : defines the shuffling number before splitting the data
* train/test_size: defines the percentage you want to used for training/testing [use in 0.2 - 0.9]
```

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.6, random_state = 101)
X_train.shape, X_test.shape

((90, 4), (60, 4))